// packages/react-template/src/components/IgntAmountSelect.tsx
/* eslint-disable jsx-a11y/no-static-element-interactions */
/* eslint-disable jsx-a11y/click-events-have-key-events */
import { useMemo, useState } from "react";
import { useDenomContext } from "../def-hooks/denomContext";
import { Amount } from "../utils/interfaces";
import { IgntAddIcon, IgntSearchIcon, IgntModal } from "@ignt/react-library";
import IgntAmountInputRow from "./IgntAmountInputRow";
import IgntDenom from "./IgntDenom";

interface IgntAmountSelectProps {
  className?: string;
  selected: Amount[];
  balances: Amount[];
  update: (amounts: Amount[]) => void;
}
export interface State {
  tokenSearch: string;
  modalOpen: boolean;
}

const initialState: State = {
  tokenSearch: "",
  modalOpen: false,
};
export default function IgntAmountSelect(props: IgntAmountSelectProps) {
  const { selected, balances, update } = props;
  const [state, setState] = useState(initialState);

  const { denoms } = useDenomContext();
  const ableToBeSelected = useMemo(() => {
    const notSelected = (x: Amount) =>
      (props.selected as Array<Amount>).every((y: Amount) => {
        return x.denom !== y.denom;
      });

    const searchFilter = (x: Amount) => {
      const base = denoms[x.denom].normalized;
      if (base.toLowerCase().includes(state.tokenSearch.toLowerCase())) {
        return true;
      } else {
        return false;
      }
    };
    return props.balances?.filter(notSelected).filter(searchFilter) ?? [];
  }, [selected, balances, state.tokenSearch]);

  const handleInputChange = (val: Amount) => {
    console.log(val);
    const newSelected: Array<Amount> = [...(selected ?? [])];
    const index = newSelected.findIndex((x) => x.denom == val.denom);
    newSelected[index].amount = val.amount;
    console.log(newSelected);
    update(newSelected);
  };
  const handleTokenSelect = (x: Amount) => {
    const newSelected: Array<Amount> = [
      ...(selected ?? []),
      {
        amount: "",
        denom: x.denom,
      },
    ];

    update(newSelected);
    setState((oldState) => ({ ...oldState, modalOpen: false }));
  };
  return (
    <div className={`flex flex-col ${props.className ?? ""}`}>
      {selected.map((x, i) => (
        <IgntAmountInputRow
          key={`${x.denom}-${i}`}
          amount={x}
          onChange={(val) => {
            handleInputChange({ amount: val, denom: x.denom });
          }}
          className="flex justify-between items-center my-1 py-3 rounded-xl relative -mx-2 px-4"
        />
      ))}

      {ableToBeSelected.length > 0 && (
        <div
          className="flex items-center text-xs font-medium text-gray-600 mt-2 px-2"
          onClick={() => {
            setState((oldState) => ({ ...oldState, modalOpen: true }));
          }}
        >
          <IgntAddIcon />
          <div className="ml-3 mt-0.5">Add asset</div>
        </div>
      )}

      <IgntModal
        visible={state.modalOpen}
        close-icon="true"
        title="Select asset"
        close={() => {
          setState((oldState) => ({ ...oldState, modalOpen: false }));
        }}
        body={
          <>
            <div className="relative mb-4">
              <IgntSearchIcon className="absolute py-3 h-12 mt-2 left-3" />
              <input
                className="mt-1 py-3 px-4 pl-8 h-12 bg-gray-100 border-xs text-base leading-tight w-full rounded-xl outline-0"
                placeholder="Search assets"
                onChange={(evt) => {
                  setState((oldState) => ({ ...oldState, tokenSearch: evt.target.value }));
                }}
              />
            </div>
            <div className="relative">
              {ableToBeSelected.map((x) => (
                <div
                  key={"balance_select_" + x.denom}
                  className="flex justify-start w-full items-center my-1 py-3 rounded-xl hover:bg-gray-100 px-2"
                  onClick={() => {
                    handleTokenSelect(x);
                  }}
                >
                  <IgntDenom denom={x.denom} modifier="avatar" />

                  <div className="flex flex-col justify-between ml-4">
                    <div className="font-semibold">
                      <IgntDenom denom={x.denom} shorten={false} />
                    </div>

                    <div className="text-xs">{x.amount} available</div>
                  </div>
                </div>
              ))}
            </div>
          </>
        }
      />
    </div>
  );
}

// packages/vue-template/src/components/IgntAmountSelect.vue
<template>
  <div class="flex flex-col">
    <IgntAmountInputRow
      v-for="(x, i) in selected"
      :key="`${x.denom}-${i}`"
      :amount="x"
      class="flex justify-between items-center my-1 py-3 rounded-xl relative -mx-2 px-4"
      @change="
        (val) => {
          handleInputChange({ amount: val, denom: x.denom });
        }
      "
    />

    <div
      v-if="ableToBeSelected.length > 0"
      class="flex items-center text-xs font-medium text-gray-600 mt-2 px-2"
      @click="
        () => {
          state.modalOpen = true;
        }
      "
    >
      <IgntAddIcon />
      <div class="ml-3 mt-0.5">Add asset</div>
    </div>

    <IgntModal
      :visible="state.modalOpen"
      :close-icon="true"
      :title="'Select asset'"
      @close="state.modalOpen = false"
    >
      <template #body>
        <div class="relative mb-4">
          <IgntSearchIcon class="absolute py-3 h-12 mt-2 left-3" />
          <input
            v-model="state.tokenSearch"
            class="mt-1 py-3 px-4 pl-8 h-12 bg-gray-100 border-xs text-base leading-tight w-full rounded-xl outline-0"
            placeholder="Search assets"
          />
        </div>
        <div class="relative">
          <div
            v-for="(x, i) in ableToBeSelected"
            :key="'balance_select_' + x.denom"
            class="flex justify-start w-full items-center my-1 py-3 rounded-xl hover:bg-gray-100 px-2"
            :index="i"
            @click="
              () => {
                handleTokenSelect(x);
              }
            "
          >
            <IgntDenom :denom="x.denom" modifier="avatar" />

            <div class="flex flex-col justify-between ml-4">
              <div class="font-semibold">
                <IgntDenom :denom="x.denom" :shorten="false" />
              </div>

              <div class="text-xs">{{ parseAmount(x.amount) }} available</div>
            </div>
          </div>
        </div>
      </template>
    </IgntModal>
  </div>
</template>

<script setup lang="ts">
import { useDenom } from "@/def-composables/useDenom";
import type { Amount } from "@/utils/interfaces";
import BigNumber from "bignumber.js";
import { computed, type PropType, reactive } from "vue";

import IgntDenom from "./IgntDenom.vue";
import { IgntModal } from "@ignt/vue-library";
import { IgntSearchIcon } from "@ignt/vue-library";
import { IgntAddIcon } from "@ignt/vue-library";
import IgntAmountInputRow from "./IgntAmountInputRow.vue";

export interface State {
  tokenSearch: string;
  modalOpen: boolean;
}

const initialState: State = {
  tokenSearch: "",
  modalOpen: false,
};

const emit = defineEmits(["update"]);

const props = defineProps({
  selected: {
    type: Array as PropType<Array<Amount>>,
  },
  balances: {
    type: Array as PropType<Array<Amount>>,
  },
});

// state
let state: State = reactive(initialState);

// computed
let ableToBeSelected = computed(() => {
  const notSelected = (x: Amount) =>
    (props.selected as Array<Amount>).every((y: Amount) => {
      return x.denom !== y.denom;
    });

  const searchFilter = (x: Amount) => {
    const base = useDenom(x.denom).normalized.value;
    if (base.toLowerCase().includes(state.tokenSearch.toLowerCase())) {
      return true;
    } else {
      return false;
    }
  };
  return props.balances?.filter(notSelected).filter(searchFilter) ?? [];
});

let parseAmount = (amount: string): BigNumber => {
  return amount == "" ? new BigNumber(0) : new BigNumber(amount);
};

const handleInputChange = (val: Amount) => {
  const newSelected: Array<Amount> = [...(props.selected ?? [])];
  const index = newSelected.findIndex((x) => x.denom == val.denom);
  newSelected[index].amount = val.amount;
  emit("update", newSelected);
};
let handleTokenSelect = (x: Amount) => {
  let newSelected: Array<Amount> = [
    ...(props.selected ?? []),
    {
      amount: "",
      denom: x.denom,
    },
  ];
  console.log(newSelected);
  emit("update", newSelected);

  state.modalOpen = false;
};
</script>
