// packages/vue-lib/src/components/IgntTabs.vue
<template>
  <div>
    <div :class="tabHeaderClasses">
      <a
        href="javascript:void(0)"
        :class="
          active != index
            ? [...tabLinkClasses, ...inactiveLinkClasses]
            : [...tabLinkClasses, ...activeLinkClasses]
        "
        v-for="(tab, index) in tabs"
        :key="index"
        @click="
          () => {
            setActive(index);
          }
        "
      >
        {{ tab.title }}
      </a>
    </div>
    <div class="tabsContent" :class="tabContentClasses" ref="tabElement">
      <slot></slot>
    </div>
  </div>
</template>
<script setup lang="ts">
import { onMounted, type PropType, ref } from "vue";
import { useSlots } from "vue";

import type { Nullable } from "@/types/interfaces";

const slots = useSlots();

defineProps({
  tabHeaderClasses: Array as PropType<Array<string>>,
  tabLinkClasses: {
    type: Array as PropType<Array<string>>,
    default: () => [],
  },
  activeLinkClasses: {
    type: Array as PropType<Array<string>>,
    default: () => [],
  },
  inactiveLinkClasses: {
    type: Array as PropType<Array<string>>,
    default: () => [],
  },
  tabContentClasses: Array as PropType<Array<string>>,
});
const tabs = ref([] as Array<{ title: string; content: unknown }>);
const tabElement = ref<Nullable<HTMLElement>>(null);
const active = ref(0);
const setActive = (slot: number) => {
  active.value = slot;
  Array.from(tabElement.value?.children ?? []).forEach((x) =>
    x.classList.remove("is-active")
  );
  tabElement.value?.children[slot].classList.add("is-active");
};
onMounted(() => {
  if (slots.default) {
    tabs.value = slots.default().map((el) => {
      return { title: el.props?.tabTitle, content: el };
    });
  }
  setActive(active.value);
});
</script>
<style>
.tabsContent > * {
  display: none;
}
.tabsContent > .is-active {
  display: block;
}
</style>

// packages/react-lib/src/components/IgntTabs.tsx
/* eslint-disable jsx-a11y/anchor-is-valid */
import {
  Children,
  cloneElement,
  DetailedHTMLProps,
  HTMLAttributes,
  ReactElement,
  ReactNode,
  useRef,
  useState,
} from "react";
import "./IgntTabs.css";

interface IgntTabsProps {
  className?: string;
  tabHeaderClasses?: string[];
  tabLinkClasses?: string[];
  activeLinkClasses?: string[];
  inactiveLinkClasses?: string[];
  tabContentClasses?: string[];
  children?: ReactNode;
}
export default function IgntTabs(props: IgntTabsProps) {
  const [active, setActive] = useState(0);
  const tabs = Children.toArray(props.children);
  const tabElement = useRef<HTMLDivElement>(null);

  return (
    <div className={props.className ?? ""}>
      <div className={props.tabHeaderClasses?.join(" ")}>
        {Children.map(tabs, (tab, index) => (
          <a
            href="javascript:void(0)"
            className={
              active != index
                ? [...(props.tabLinkClasses || []), ...(props.inactiveLinkClasses || [])].join(" ")
                : [...(props.tabLinkClasses || []), ...(props.activeLinkClasses || [])].join(" ")
            }
            key={"tab_" + index}
            onClick={() => {
              setActive(index);
            }}
          >
            {((tab as ReactElement).props as DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>).title}
          </a>
        ))}
      </div>
      <div className={"tabsContent " + (props.tabContentClasses || []).join(" ")} ref={tabElement}>
        {Children.map(props.children, (child, index) => {
          if (active == index) {
            return cloneElement(
              child as ReactElement,
              {
                ...(child as ReactElement).props,
                className:
                  (((child as ReactElement).props as DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>)
                    .className ?? "") + " is-active",
              },
              (child as ReactElement).props.children,
            );
          } else {
            return child;
          }
        })}
      </div>
    </div>
  );
}
IgntTabs.defaultProps = {
  tabHeaderClasses: [],
  tabLinkClasses: [],
  activeLinkClasses: [],
  inactiveLinkClasses: [],
  tabContentClasses: [],
};
