// packages/vue-template/src/components/IgntHeader.vue
<template>
  <header class="flex p-5">
    <IgntLogo class="mx-2.5" />
    <nav class="flex flex-1 justify-between">
      <ul class="flex items-center">
        <li
          class="text-3 px-4 font-normal"
          v-for="item in navItems"
          :key="item.label"
        >
          <IgntLink :item="item"></IgntLink>
        </li>
      </ul>
      <div><IgntAcc /></div>
    </nav>
  </header>
</template>
<script setup lang="ts">
import { IgntLink } from "@ignt/vue-library";
import { IgntLogo } from "@ignt/vue-library";
import { type PropType, ref } from "vue";

import IgntAcc from "@/components/IgntAcc.vue";

type MenuItem = {
  label: string;
  to?: string;
  href?: string;
};
const props = defineProps({
  navItems: {
    type: Array as PropType<Array<MenuItem>>,
    required: true,
  },
});
const navItems = ref(props.navItems);
</script>

// packages/react-template/src/components/IgntHeader.tsx
import { IgntLink, IgntLogo } from "@ignt/react-library";
import IgntAcc from "./IgntAcc";

type MenuItem = {
  label: string;
  to?: string;
  href?: string;
};
interface IgntHeaderProps {
  navItems: Array<MenuItem>;
}
export default function IgntHeader(props: IgntHeaderProps) {
  const { navItems } = props;

  return (
    <header className="flex p-5">
      <IgntLogo className="mx-2.5" />
      <nav className="flex flex-1 justify-between">
        <ul className="flex items-center">
          {navItems.map((item) => (
            <li className="text-3 px-4 font-normal" key={item.label}>
              <IgntLink item={item}></IgntLink>
            </li>
          ))}
        </ul>

        <div>
          <IgntAcc />
        </div>
      </nav>
    </header>
  );
}
