// packages/react-template/src/components/for_react_lib/IgntLink.tsx
import { useEffect, useState } from 'react'
import { useLocation } from 'react-router-dom'
import { Link } from "react-router-dom";

type MenuItem = {
  label: string;
  to?: string;
  href?: string;
};
interface IgntLinkProps {
  item: MenuItem
}
export default function IgntLink(props: IgntLinkProps) {
  const location = useLocation();
  const { item } = props;
  const [isActive, setActive] = useState(item.to == location.pathname);

  useEffect(() => {
    setActive(item.to == location.pathname)
  }, [location.pathname]);

  if (item.to) {
    return (<Link to={item.to} className={isActive ? "opacity-100 font-medium" : "opacity-50"}>{item.label}</Link>)
  } else {
    return (<a href="{item.href}" className={isActive ? "opacity-100 font-medium" : "opacity-50"}>{item.label}</a>)
  }
}

// packages/vue-lib/src/components/IgntLink.vue
<template>
  <RouterLink
    :class="{ 'opacity-50': !isActive }"
    activeClass="opacity-100 font-medium"
    v-if="item.to"
    :to="item.to"
    >{{ item.label }}</RouterLink
  >
  <a v-else :href="item.href">{{ item.label }}</a>
</template>
<script setup lang="ts">
import { ref, watch, type PropType } from "vue";
import { useRouter } from "vue-router";
const router = useRouter();
type MenuItem = {
  label: string;
  to?: string;
  href?: string;
};
const props = defineProps({
  item: {
    type: Object as PropType<MenuItem>,
    required: true,
  },
});
const item = ref(props.item);
const isActive = ref(false);
watch(
  () => router.currentRoute.value.path,
  () => {
    if (item.value.to && item.value.to === router.currentRoute.value.path) {
      isActive.value = true;
    } else {
      isActive.value = false;
    }
  }
);
</script>
