// packages/react-template/src/components/for_react_lib/IgntModal.tsx
/* eslint-disable jsx-a11y/no-noninteractive-element-interactions */
/* eslint-disable jsx-a11y/no-noninteractive-tabindex */
/* eslint-disable jsx-a11y/click-events-have-key-events */
/* eslint-disable jsx-a11y/no-static-element-interactions */
import { ReactNode, useEffect } from "react";
import IgntTimesIcon from "./icons/IgntTimesIcon";
import IgntButton from "./IgntButton";
import IgntCard from "./IgntCard";

interface IgntModalProps {
  visible?: boolean;
  submitButton?: boolean;
  cancelButton?: boolean;
  closeIcon?: boolean;
  title?: string;
  header?: ReactNode;
  body?: ReactNode;
  footer?: ReactNode;
  submit?: () => void;
  close?: () => void;
}
export default function IgntModal(props: IgntModalProps) {
  const escapeHandler = (evt: { key: string }) => {
    if (evt.key === "Escape") props.close && props.close();
  };
  /*
  useEffect(()=>)
    () => props.visible,
    (newVal) => {
      if (newVal) {
        document.addEventListener("keyup", escapeHandler);
      } else {
        document.removeEventListener("keyup", escapeHandler);
      }
    }
  );*/
  return (
    <>
      {props.visible && (
        <div
          className="fixed inset-0 flex justify-center items-center bg-gray-330"
          onClick={() => props.close && props.close()}
        >
          <div
            className="shadow-std relative max-h-screen text-center"
            role="dialog"
            tabIndex={0}
            onClick={(e) => {
              e.stopPropagation();
            }}
          >
            <IgntCard
              className="px-6 py-4 max-h-screen overflow-y-auto scroll-smooth"
              header={
                props.header ? (
                  props.header
                ) : (
                  <h3 className="text-center text-2xl font-semibold my-4 mb-6">{props.title || "Default title"}</h3>
                )
              }
              footer={
                props.footer ? (
                  props.footer
                ) : (
                  <div className="flex flex-col">
                    {props.submitButton && (
                      <IgntButton
                        aria-label="Submit"
                        className="mb-2"
                        type="primary"
                        onClick={() => props.submit && props.submit()}
                      >
                        Save changes
                      </IgntButton>
                    )}
                    {props.cancelButton && (
                      <IgntButton
                        aria-label="Close modal"
                        type="secondary"
                        onClick={() => props.close && props.close()}
                      >
                        Cancel
                      </IgntButton>
                    )}
                  </div>
                )
              }
            >
              {props.body}
            </IgntCard>
            {props.closeIcon && (
              <span onClick={() => props.close && props.close()}>
                <IgntTimesIcon className="absolute right-8 top-10 cursor-pointer" />
              </span>
            )}
          </div>
        </div>
      )}
    </>
  );
}
IgntModal.defaultProps = {
  visible: false,
  title: null,
  submitButton: true,
  cancelButton: true,
  closeIcon: true,
};

// packages/vue-lib/src/components/IgntModal.vue
<template>
  <transition name="modal-fade">
    <div
      v-if="visible"
      class="fixed inset-0 flex justify-center items-center bg-gray-330 z-50"
      @click="emit('close')"
    >
      <div
        class="shadow-std relative max-h-screen"
        role="dialog"
        tabindex="0"
        @click.stop
      >
        <IgntCard class="px-6 py-4 max-h-screen overflow-y-auto scroll-smooth">
          <template #header>
            <slot name="header">
              <h3 class="text-center text-2xl font-semibold my-4 mb-6">
                {{ title || "Default title" }}
              </h3>
            </slot>
          </template>

          <template #default>
            <slot name="body"></slot>
          </template>

          <template #footer>
            <slot name="footer">
              <div class="flex flex-col">
                <IgntButton
                  v-if="submitButton"
                  aria-label="Submit"
                  class="mb-2"
                  type="primary"
                  @click="emit('submit')"
                >
                  Save changes
                </IgntButton>
                <IgntButton
                  v-if="cancelButton"
                  aria-label="Close modal"
                  type="secondary"
                  @click="emit('close')"
                >
                  Cancel
                </IgntButton>
              </div>
            </slot>
          </template>
        </IgntCard>

        <IgntTimesIcon
          v-if="closeIcon"
          class="absolute right-8 top-10 cursor-pointer"
          @click="emit('close')"
        >
          Close
        </IgntTimesIcon>
      </div>
    </div>
  </transition>
</template>

<script setup lang="ts">
import { watch } from "vue";

import IgntTimesIcon from "./icons/IgntTimesIcon.vue";
import IgntButton from "./IgntButton.vue";
import IgntCard from "./IgntCard.vue";
const emit = defineEmits(["close", "submit"]);
const props = defineProps({
  visible: {
    type: Boolean,
    defaultsTo: false,
  },
  title: {
    type: String,
    defaultsTo: null,
  },
  submitButton: {
    type: Boolean,
    defaultsTo: true,
  },
  closeIcon: {
    type: Boolean,
    defaultsTo: true,
  },
  cancelButton: {
    type: Boolean,
    defaultsTo: true,
  },
});
const escapeHandler = (evt: { key: string }) => {
  if (evt.key === "Escape") emit("close");
};
watch(
  () => props.visible,
  (newVal) => {
    if (newVal) {
      document.addEventListener("keyup", escapeHandler);
    } else {
      document.removeEventListener("keyup", escapeHandler);
    }
  }
);
</script>
