// packages/react-template/src/components/for_react_lib/IgntQRCode.tsx
import { toCanvas } from "qrcode";
import { useRef } from "react";

interface IgntQRCodeProps {
  value?: string;
  width?: number;
  background?: string;
  color?: string;
  className?: string;
}
export default function IgntQRCode(props: IgntQRCodeProps) {
  const canvas = useRef<HTMLCanvasElement>(null);
  const options = {
    margin: 0,
    width: props.width,
    color: {
      dark: props.color,
      light: props.background,
    },
  };

  toCanvas(canvas.current, props.value ?? "", options);

  return <canvas ref={canvas} className={"qr-code " + (props.className ?? "")} />;
}
IgntQRCode.defaultProps = {
  value: "",
  width: 100,
  background: "#0000",
  color: "#000000ff",
};

// packages/vue-lib/src/components/IgntQRCode.vue
<template>
  <canvas ref="canvas" class="qr-code" />
</template>

<script setup lang="ts">
import { toCanvas } from "qrcode";
import { onMounted, ref, watch } from "vue";

const props = defineProps({
  value: {
    type: String,
    default: "",
  },
  width: {
    type: Number,
    default: 100,
  },
  background: {
    type: String,
    default: "#0000", // Transparent
  },
  color: {
    type: String,
    default: "#000000ff",
  },
});
// state
const canvas = ref(null);

// methods
const generate = () => {
  const options = {
    margin: 0,
    width: props.width,
    color: {
      dark: props.color,
      light: props.background,
    },
  };

  toCanvas(canvas.value, props.value, options);
};

// lh
onMounted(generate);

// watch
watch(props, generate);
</script>

<style scoped lang="scss"></style>
