// packages/react-template/src/views/PortfolioView.tsx
/* eslint-disable jsx-a11y/no-static-element-interactions */
/* eslint-disable jsx-a11y/click-events-have-key-events */
import IgntAssets from "../components/IgntAssets";
import IgntTransactions from "../components/IgntTransactions";
import IgntTransfer from "../components/IgntTransfer";
import { useAddressContext } from "../def-hooks/addressContext";

export default function PortfolioView() {
  const address = useAddressContext();
  return (
    <div>
      <div className="container mx-auto">
        <div className="grid grid-cols-2">
          <div>
            {address.address && (
              <>
                <IgntAssets className="px-2.5 mb-10" displayLimit={3} />
                <IgntTransactions className="px-2.5" />
              </>
            )}
          </div>
          <IgntTransfer className="px-2.5 w-4/6 mx-auto" />
        </div>
      </div>
    </div>
  );
}

// packages/vue-template/src/views/PortfolioView.vue
<template>
  <div>
    <div class="container mx-auto">
      <div class="grid grid-cols-2">
        <div>
          <IgntAssets :key="address" class="px-2.5 mb-10" :display-limit="3" />
          <IgntTransactions :key="address" class="px-2.5" />
        </div>
        <IgntTransfer class="px-2.5 w-4/6 mx-auto" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useAddress } from "@/def-composables/useAddress";

import IgntAssets from "../components/IgntAssets.vue";
import IgntTransactions from "../components/IgntTransactions.vue";
import IgntTransfer from "../components/IgntTransfer.vue";
const { address } = useAddress();
</script>
