// packages/vue-lib/src/components/IgntClipboard.vue
<template>
  <IgntButton @click="() => copy(text)" type="plain">
    <IgntCopyIcon
  /></IgntButton>
</template>
<script setup lang="ts">
import type { PropType } from "vue";

import { useClipboard } from "@/def-composables/useClipboard";

import IgntCopyIcon from "./icons/IgntCopyIcon.vue";
import IgntButton from "./IgntButton.vue";

defineProps({
  text: {
    type: String as PropType<string>,
    default: () => "",
  },
});
const { copy } = useClipboard();
</script>

// packages/react-template/src/components/for_react_lib/IgntClipboard.tsx
import { useClipboard } from "../../def-hooks/useClipboard";
import IgntCopyIcon from "./icons/IgntCopyIcon";
import IgntButton from "./IgntButton";

interface IgntClipboardProps {
  text?: string;
  className?: string;
}
export default function IgntClipboard(props: IgntClipboardProps) {
  const { copy } = useClipboard();
  return (
    <IgntButton onClick={() => copy(props.text ?? "")} type="plain" className={props.className ?? ""}>
      <IgntCopyIcon />
    </IgntButton>
  );
}
IgntClipboard.defaultProps = {
  text: "",
};
